// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sssmxxigyipnqcaxpsfx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNzc214eGlneWlwbnFjYXhwc2Z4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyNTk1ODEsImV4cCI6MjA3MjgzNTU4MX0.M2b3yDzhS2ZGcy60wgjLz66Byevy7_EKiVNZKu3u1Uk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});